version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_USER=alexandra
      - POSTGRES_PASSWORD=alex55
      - POSTGRES_DB=flask_db
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - database_value:/var/lib/postgresql/data/

volumes:
  database_value: